Integration tests passing

diff --git a/tests/00-setup b/tests/00-setup
--- a/tests/00-setup
+++ b/tests/00-setup
@@ -8,3 +8,13 @@ if ! dpkg -s amulet; then
     sudo apt-get update
     sudo apt-get install -y amulet
 fi
+
+# Check that the Jenkins client is available
+if ! dpkg -s python3-jenkins; then
+    sudo apt-get install -y python3-jenkins
+fi
+
+# Check that python retrying is available
+if ! dpkg -s python3-retrying; then
+    sudo apt-get install python3-retrying
+fi
